import React, { Component } from 'react';
import axios from 'axios';
import FixedDataTable from 'fixed-data-table';
import apiConfig from '../config.json';
import './RaidProgress.css';
import 'bootstrap/dist/css/bootstrap.css';
import 'fixed-data-table/dist/fixed-data-table-base.css';
import 'fixed-data-table/dist/fixed-data-table-style.css';
import 'fixed-data-table/dist/fixed-data-table.css';

let api = apiConfig.api;
const { Table, Column, Cell } = FixedDataTable;

class RaidProgress extends Component {

  constructor(props) {
    super(props);

    this.bank_name = [
      "1st Capital Bank",
      "1st Commonwealth Bank of Virginia",
      "1st Manatee Bank",
      "1st Manatee Bank (Amended)",
      "1st Performance Business Bank",
      "@Bank",
      "A.G. Edwards Trust Co, FSB",
      "AAL Trust Company",
      "Access 1st Capital Bank",
      "Access Bank",
      "Access Business Bank*",
      "Adams Dairy Bank",
      "Aetna Trust Company, FSB",
      "Allegiance Bank Texas",
      "Allegiance Direct Bank",
      "Alliance, FSB",
      "Allstate Federal Savings Bank",
      "AloStar Bank of Commerce",
      "AloStar Bank of Commerce (Modified)",
      "American Bank of Florida",
      "American Eagle Bank of Chicago",
      "American Express Personal Trust Services, FSB",
      "American Plus Bank, N.A.",
      "American Premier Bank",
      "American Pride Bank",
      "American Principle Bank",
      "AMG National Trust Bank",
      "Anderen Bank of Tampa Bay",
      "Ann Arbor State Bank",
      "Appalachian Community Bank, F.S.B.",
      "ARCUS Financial Bank",
      "ARCUS Financial Bank (Modifed)",
      "Asiana Bank",
      "Assurance Partners Bank",
      "Atlantic Capital Bank",
      "Austin County State Bank",
      "Auto Club Trust, FSB",
      "Banco BuenaVentura",
      "Bandera First State Bank",
      "Bank 1440",
      "Bank Midwest, National Association",
      "Bank of America Illinois, National Association",
      "Bank of America Michigan, National Association",
      "Bank of Austin (The)",
      "Bank of Bird-in-Hand",
      "Bank of Central Florida",
      "Bank of Fairfield (The)",
      "Bank of Feather River",
      "Bank of Fort Bend",
      "Bank of George",
      "Bank of Hawaii Credit Card, National Association",
      "Bank of Las Colinas",
      "Bank of Manhattan, NA",
      "Bank of Montana",
      "Bank of Princeton (The)",
      "Bank of Sacramento",
      "Bank of San Antonio",
      "Bank of the Republic",
      "BankAsiana",
      "BankBlackwell, FSB",
      "Bankers Trust Company, National Association",
      "BankUnited, FSB",
      "Bay Bank, FSB",
      "Baytree National Bank & Trust Company",
      "BBU Bank",
      "Beal Savings Bank",
      "Belk National Bank",
      "Black Hills Community Bank, N.A.",
      "BlackRidgeBANK",
      "Blue Gate Bank",
      "Bluegrass Community Bank",
      "BlueHarbor Bank",
      "BlueRidge Bank",
      "BMW Bank of North America, Inc.",
      "BPA Bank, N.A.",
      "Brookhaven Bank",
      "Broward Bank of Commerce",
      "Burr Ridge Bank and Trust",
      "Business Bank, National Association",
      "California Bank of Commerce*",
      "California First National Bank",
      "California General Bank, N.A.",
      "California Republic Bank",
      "Calusa National Bank",
      "Capital Bank *",
      "Capital Bank and Trust Company",
      "CapitalMark Bank & Trust",
      "CapitalSource Bank",
      "CapitalSource Bank",
      "CapStar Bank",
      "Cardinal Creek Savings Bank",
      "Carolina Premier Bank",
      "CBank",
      "CenterPointe Community Bank",
      "Centura Card Bank",
      "CertusBank, NA",
      "Chain Bridge Bank, N.A.",
      "Charter Alliance Bank",
      "Charter Bank",
      "Charter Bank",
      "Chattahoochee Bank of Georgia",
      "CheckSpring Bank",
      "CheckSpring Bank",
      "CIBC National Bank",
      "CIT OnLine Bank",
      "Citizens Business Bank*",
      "CNLBank, Southwest Florida",
      "Coastal Bank & Trust",
      "Coastal Carolina National Bank",
      "Coastway Community Bank",
      "Collin Bank",
      "Colonia Bank",
      "Colony Signature Bank",
      "Columbus First Bank",
      "Commerce Bank of Temecula Valley*",
      "Community & Southern Bank",
      "Community 1st Bank",
      "Community Bank (The)",
      "Community Bank of Lincoln",
      "Community Bank, Destin",
      "Community Business Bank",
      "Community Capital Bank of Virginia",
      "Community First Bank",
      "Community First Bank of Georgia",
      "Community National Bank",
      "Community State Bank",
      "Community Valley Bank",
      "Compass Community Bank",
      "CompuBank, N.A.",
      "CompuBank, N.A.(Reconsideration)",
      "Core Business Bank",
      "Core Commercial Bank",
      "CornerStone Bank, N.A.",
      "Cornerstone Federal Bank",
      "Country Trust Bank, FSB",
      "CrossPoint Bank",
      "Davidson Trust Co.",
      "Delafield State Bank",
      "Department Stores National Bank",
      "E*TRADE Savings Bank",
      "Eagle Bank",
      "Earthstar Bank",
      "Embarcadero Bank",
      "Empire National Bank",
      "EnerBank USA",
      "Escrow Bank USA",
      "Farm Bureau, Federal Savings Bank",
      "Fidelity Personal Trust Company, FSB",
      "Fieldpoint Private Bank & Trust",
      "Fifth Street Bank",
      "FineMark National Bank & Trust",
      "First American Bank, N.A.",
      "First Asian Bank",
      "First Associations Bank",
      "First Bank",
      "First Bank of Commerce, N.A.",
      "First Cahawba Bank",
      "First Choice Bank",
      "First Choice Community Bank",
      "First Colony Bank of Florida",
      "First Commons Bank, National Association",
      "First Community Bank of Homer Glen & Lockport",
      "First Community Bank of Plainfield",
      "First Foundation Bank",
      "First Green Bank",
      "First Hawaiian BankCard, National Association",
      "First Internet Bank of Indiana",
      "First Landmark Bank",
      "First Milton Bank",
      "First National Bank of Scottsdale",
      "First National Bank of Steamboat Springs",
      "First National Bank of the Gulf Coast",
      "First National Bank of the Gulf Coast",
      "First New Mexico Bank",
      "First Private Bank of Texas",
      "First Republic Bank",
      "First Retail Bank, N.A.",
      "First Security Bank of Lexington, Inc.",
      "First Spirit Bank*",
      "First Virginia Community Bank",
      "First Western Trust Bank of Arizona",
      "FirstCity Bank of Commerce",
      "Florida Shores Bank-Southwest",
      "Florida Traditions Bank",
      "Flushing Commercial Bank",
      "Foothills Bank & Trust",
      "Forest Commercial Bank",
      "Forethought Federal Savings Bank",
      "Foundation National Bank",
      "Founders Bank & Trust, National Association",
      "Founders Bank, SSB",
      "FPC Financial, f.s.b.",
      "Franklin Synergy Bank",
      "Freedom Bank",
      "Frontier Bank of Texas",
      "Frontier Community Bank",
      "Frontier Trust Company, FSB",
      "G & L Bank",
      "Gateway Bank of Central Florida",
      "Gateway Bank of Southwest Florida",
      "Gateway Commercial Bank",
      "Gateway Pacific Bank",
      "Generations Bank",
      "Generations Bank",
      "Georgia Primary Bank (formerly Primary Bank)",
      "Georgica Bank, National Association",
      "Global Trust Bank",
      "GMAC Automotive Bank",
      "GMAC Bank",
      "GMAC Bank (Amended)",
      "GMAC Commercial Mortgage Bank",
      "Gold Coast Bank",
      "Gold Coast Bank",
      "Golden Eagle Community Bank",
      "Goldman Sachs Bank USA",
      "Grand River Bank",
      "Grange Bank (The)",
      "Great Nations Bank",
      "Great Northern Bank",
      "Great State Bank",
      "Greenwich Bank & Trust (The)",
      "Greystone Bank",
      "Guadalupe National Bank",
      "Guaranty Bank, S.S.B.",
      "Guardian Trust Company, FSB",
      "GulfShore Bank",
      "Hanover Community Bank",
      "HarborOne Bank",
      "Harmony Bank",
      "Hartford Bank (The)",
      "HealthBenefit Bank d/b/a Blue Healthcare Bank",
      "Heritage Bank, N.A.",
      "High Desert Bank",
      "Hillcrest Bank, NA",
      "Hometown Bank of Pennsylvania",
      "Houston Business Bank",
      "INA Trust, fsb",
      "Independence Bank",
      "Independence Bank of Georgia",
      "Independence Trust Company",
      "Infinity Bank",
      "ING Bank, FSB",
      "Institutional Trust Company",
      "InsurBanc, FSB",
      "Insurors Bank of Tennessee",
      "Integrity Bank, S.S.B.",
      "International Bank of Commerce",
      "Intracoastal Bank",
      "Issaquah Community Bank",
      "Jefferson Bank of Florida",
      "JPMorgan Bank and Trust Company, National Association",
      "KeySource Commercial Bank",
      "KeyWorth Bank",
      "Kirkwood Bank of Nevada",
      "LaGrange Banking Company",
      "Lake Sammamish Bank*",
      "Lakeside Bank",
      "Larimer Bank of Commerce",
      "LCA Bank Corporation",
      "Lehman Brothers Commercial Bank",
      "Level One Bank*",
      "Liberty Bank of Washington",
      "Liberty Capital Bank",
      "Lighthouse Bank",
      "Lighthouse Bank",
      "Live Oak Banking Company",
      "Lone Star State Bank of West Texas",
      "Loveland Bank of Commerce",
      "M&I Bank of Mayville",
      "Madison National Bank",
      "Madison National Bank (Amended)",
      "Magnet Bank",
      "Magnet Bank (Modified)",
      "Manchester Financial Bank, N.A.",
      "Marlin Business Bank",
      "Marlin Business Bank (Modified)",
      "Maryland Financial Bank",
      "MassMutual Trust Company",
      "Meadows Bank",
      "Medallion Bank",
      "Mega Bank",
      "Members Trust Company",
      "Memorial City Bank",
      "Mercantile Trust Co, N.A.",
      "Metro Bank",
      "Metro Phoenix Bank",
      "Michigan Community Savings Bank, successor to Community Schools Credit Union",
      "Michigan Trust Bank",
      "MidCoast Community Bank",
      "MileStone Bank",
      "MileStone Bank (Modified)",
      "Milltown Banking Company",
      "Minnesota Bank & Trust",
      "MINT National Bank (The)",
      "MMA Trust Company",
      "Monument Bank",
      "Mountain View Bank of Commerce",
      "MRV Banks",
      "MWABank, FSB",
      "NAFH, NB",
      "Nashua Bank (The)",
      "National Advisors Trust Company, FSB",
      "Nationwide Trust Co, FSB",
      "Nevada National Bank",
      "Nevada Pacific Bank",
      "New Century Bank",
      "New Century Bank",
      "New Horizon Bank, National Association",
      "New Jersey Community Bank",
      "New Security First Network Bank",
      "New Traditions National Bank",
      "New York Life Trust Company, FSB",
      "NOA Bank",
      "NorthStar Bank",
      "Northtown Bank (formerly Access Bank)",
      "NuAmerica Bank",
      "Nuestro Banco",
      "Nuvo Bank & Trust Company",
      "Nuvo Bank & Trust Company (Modified)",
      "Oak View National Bank (formerly Oak Hill National Bank)",
      "Oakworth Capital Bank",
      "Oasis Bank, S.S.B.",
      "Old Dominion National Bank",
      "Oldtown Bank",
      "One South Bank",
      "OneCalifornia Bank, FSB",
      "OneWest Bank, FSB",
      "Opportunity Bank, N.A.",
      "Optima Bank & Trust Company",
      "Overland Bank",
      "Pacific Bank",
      "Palm Beach Community Bank",
      "Panther Community Bank, National Association",
      "Paramount Bank (formerly Paramount Bank Nevada)",
      "Parkside Financial Bank & Trust",
      "Partners Bank of California",
      "Philadelphia Trust Company (The)",
      "Pioneer Bank, SSB",
      "Pisgah Community Bank",
      "Platinum Bank",
      "Platinum Bank",
      "Plus International Bank",
      "Pocono Community Bank",
      "Pointpathbank, National Association",
      "Poplar Creek Community Bank*",
      "Premier American Bank, NA",
      "Premier Commercial Bank",
      "Prestige Community Bank",
      "Prestige Community Bank (Modified)",
      "Primary Bank",
      "Prime Bank",
      "Prime Bank (Amended)",
      "Prime Meridian Bank",
      "Principal Bank",
      "Private Bank of California (The)",
      "Private Wealth Trust Company (The)",
      "ProBank",
      "Professional Bank",
      "Progress Bank and Trust",
      "Providence Bank of Texas, SSB",
      "Pyramis Global Advisors Trust Company",
      "Quinnipiac Bank & Trust Company",
      "R Bank",
      "RBS National Bank",
      "Redstone Bank",
      "Regent Bank",
      "Regional Bank of Middle Georgia",
      "Reliance Bank",
      "Republic Bank, Inc.",
      "RepublicBankAZ, National Association",
      "Resurgens Bank",
      "Reunion Bank of Florida",
      "Revere Bank",
      "RomAsia Bank",
      "Royal Bank",
      "Royal Business Bank",
      "Sallie Mae Bank",
      "San Diego Private Bank",
      "Sanford Institution for Savings",
      "Savannah River Banking Company",
      "Savoy Bank",
      "Scottrade Bank",
      "Security Bank of the Coast",
      "SEI Federal Trust Company, FSB",
      "Select Bank",
      "Settlers Bank*",
      "Shamrock Bank of Florida",
      "ShoreBank, Detroit",
      "Signature Bank",
      "SoCal Business Bank, N.A.",
      "Solera National Bank",
      "South Atlantic Bank",
      "South Louisiana Business Bank",
      "South Shore Community Bank & Trust Company",
      "SouthCity Bank",
      "Southern States Bank",
      "Spring Bank (formerly State Bank of Wisconsin)",
      "Springfield First Community Bank",
      "Square 1 Bank",
      "Start Community Bank",
      "State Bank of Georgia",
      "State Bank of Georgia (Modified)",
      "State Farm Financial Services, FSB",
      "StoneCrest National Bank of Austin",
      "Summit Bank, N.A.",
      "Summit Community Bank",
      "SunBank, National Association",
      "Suncrest Bank",
      "Sunrise Bank of Norman",
      "Sunrise Community Bank",
      "Sunshine Savings Bank",
      "Superior Bank, NA",
      "T. Rowe Price Savings Bank",
      "Talbots Classics National Bank",
      "Target Bank",
      "Tarpon Coast National Bank",
      "TB.com Bank",
      "Texas Security Bank (formerly Texas Trinity Bank)",
      "Think Mutual Bank",
      "Third Coast Bank, SSB",
      "TIAA-CREF Trust Company",
      "Touchmark National Bank (formerly Touchstone National Bank)",
      "Tower Bank of Central Indiana*",
      "Town & Country Bank",
      "Town North Bank Nevada, N.A.",
      "Toyota Financial Savings Bank",
      "Trust Company (The)",
      "Trust Company of Virginia (The)",
      "Trust Industrial Bank",
      "Turtle Mountain State Bank",
      "U.S. Trust Company of North Carolina",
      "UBS Bank USA",
      "Unified Banking Company",
      "Union Credit Bank",
      "United Community Bank, N.A.",
      "Uniti Bank",
      "Urban Partnership Bank",
      "USNY Bank",
      "Valley Republic Bank",
      "Valliance Bank",
      "Vantage Point Bank",
      "Vantage Point Bank (Modified)",
      "Veritas Bank",
      "Verity Bank",
      "Vibra Bank",
      "Victory Bank (The)",
      "Victory Community Bank",
      "Vinings Bank",
      "Virginia National Bank",
      "Virginia Partners Bank",
      "VirtualBank",
      "VistaBank",
      "Volkswagen Bank USA",
      "Volvo Commercial Credit Corp of Utah",
      "Wachovia Card Services, NA",
      "Warwick Commercial Bank (The)",
      "Waterford Bank, N.A.",
      "Wedbush Bank, FSB",
      "Wellington Trust Company, National Association",
      "Westchester Bank (The)",
      "Western Capital Bank",
      "Westfield Bank, FSB",
      "World Financial Capital Bank",
      "World's Foremost Bank, National Association",
      "WPS Community Bank, FSB",
      "Your:)Bank.com"
    ];

    this.bank_location_city = [
      "Monterey",
      "Arlington",
      "Parrish",
      "Parrish",
      "Pensacola",
      "Framingham",
      "St. Louis",
      "Appleton",
      "Denton",
      "Omaha",
      "Irvine",
      "Blue Springs",
      "Hartford",
      "Houston",
      "Cedar City",
      "Niles",
      "Northbrook",
      "Birmingham",
      "Birmingham",
      "Pinecrest",
      "Chicago",
      "Minneapolis",
      "Arcadia",
      "Arcadia",
      "Macon",
      "San Luis Obispo",
      "Boulder",
      "Palm Harbor",
      "Ann Arbor",
      "McCaysville",
      "Salt Lake City",
      "Salt Lake City",
      "Sunnyvale",
      "Carmel",
      "Atlanta",
      "Bellville",
      "Dearborn",
      "Oxnard",
      "Bandera",
      "Peoria",
      "Kansas City",
      "Chicago",
      "Troy",
      "Austin",
      "Bird-in-Hand",
      "Lakeland",
      "Fairfield",
      "Yuba City",
      "Sugar Land",
      "Las Vegas",
      "Phoenix",
      "Irving",
      "El Segundo",
      "Missoula",
      "Princeton",
      "Sacramento",
      "San Antonio",
      "Carrollton",
      "Palisades Park",
      "Boston",
      "Phoenix",
      "Coral Gables",
      "Lutherville",
      "Chicago",
      "Coral Gables",
      "Las Vegas",
      "Norcross",
      "Rapid City",
      "Fargo",
      "Costa Mesa",
      "Danville",
      "Mooresville",
      "Frederick",
      "Salt Lake City",
      "Newark",
      "Atlanta",
      "Fort Lauderdale",
      "Burr Ridge",
      "Austin",
      "Lafayette",
      "Santa Ana",
      "Pasadena",
      "Newport Beach",
      "Punta Gorda",
      "San Juan Capistrano",
      "Brea",
      "Chattanooga",
      "Pasadena",
      "Salt Lake City",
      "Nashville",
      "Mokena",
      "Charlotte",
      "Cincinnati",
      "Hood River",
      "Norcross",
      "Easley",
      "McLean",
      "Corpus Christi",
      "Albuquerque",
      "Biloxi",
      "Gainesville",
      "Bronx County",
      "Bronx County",
      "Maitland",
      "Salt Lake City",
      "Goodyear",
      "Bonita Springs",
      "Jacksonville",
      "Myrtle Beach",
      "Cranston",
      "Frisco",
      "Phoenix",
      "Charlotte",
      "Worthington",
      "Murrieta",
      "Atlanta",
      "Post Falls",
      "Bridgeport",
      "Lincoln",
      "Miramar Beach",
      "Cumming",
      "Christiansburg",
      "Somerset",
      "Elberton",
      "Waterloo",
      "Lamar",
      "El Centro",
      "Seaside",
      "Houston",
      "Houston",
      "Bellevue",
      "Newport Beach",
      "Lexington",
      "Troy",
      "Bloomington",
      "Overland Park",
      "Great Falls",
      "Delafield",
      "Sioux Falls",
      "Arlington",
      "Polson",
      "Upper Southhampton Township",
      "San Diego",
      "Islandia",
      "Salt Lake City",
      "Midvale",
      "Sparks",
      "Boston",
      "Greenwich",
      "Las Vegas",
      "Fort Myers",
      "Hudson",
      "Las Vegas",
      "Dallas",
      "Williamstown",
      "Scottsboro",
      "Selma",
      "Lawrenceville",
      "Dallas",
      "Maitland",
      "Newton",
      "Homer Glen",
      "Plainfield",
      "Irvine",
      "Eustis",
      "Scottsdale",
      "Indianapolis",
      "Marietta",
      "Milton",
      "Scottsdale",
      "Steamboat Springs",
      "Naples",
      "Naples",
      "Las Cruces",
      "Dallas",
      "San Francisco",
      "Flowery Branch",
      "Lexington",
      "Detroit",
      "Fairfax",
      "Scottsdale",
      "North Palm Beach",
      "Venice",
      "Dade City",
      "North New Hyde Park",
      "Maryville",
      "Asheville",
      "Batesville",
      "Marietta",
      "Leesburg",
      "Sugar Land",
      "Madison",
      "Franklin",
      "Oradell",
      "Elgin",
      "Waynesboro",
      "Fargo",
      "Pensacola",
      "Ocala",
      "Sarasota",
      "Mesa",
      "National City",
      "Centre",
      "Kansas City",
      "Atlanta",
      "Bridgehampton",
      "Mountain View",
      "Midvale",
      "Wilmington",
      "Wilmington",
      "Midvale",
      "Islandia",
      "Chicago",
      "Woodstock",
      "Salt Lake City",
      "Grandville",
      "Columbus",
      "Norman",
      "Antioch",
      "Wilkesboro",
      "Greenwich",
      "Raleigh",
      "Kerrville",
      "Dallas",
      "New York",
      "Tampa",
      "Garden City Park",
      "Brockton",
      "Jackson",
      "Hartford",
      "Sandy",
      "New York",
      "Bend",
      "Overland",
      "Everett",
      "Houston",
      "Philadelphia",
      "Newport Beach",
      "Braselton",
      "Franklin",
      "Santa Ana",
      "Wilmington",
      "Denver",
      "Farmington",
      "Nashville",
      "Houston",
      "Oklahoma City",
      "Palm Coast",
      "Issaquah",
      "Oldsmar",
      "San Francisco",
      "Durham",
      "Johns Creek",
      "Las Vegas",
      "LaGrange",
      "Issaquah",
      "Lake Charles",
      "Fort Collins",
      "Park County",
      "Salt Lake City",
      "Farmington Hills",
      "Poulsbo",
      "Addison",
      "Santa Cruz",
      "Waltham",
      "Wilmington",
      "Lubbock",
      "Loveland",
      "Mayville",
      "Merrick",
      "Merrick",
      "Salt Lake City",
      "Salt Lake City",
      "La Jolla",
      "Salt Lake City",
      "Salt Lake City",
      "Towson",
      "Hartford",
      "Las Vegas",
      "Salt Lake City",
      "San Gabriel",
      "Tampa",
      "Houston",
      "St. Louis",
      "Douglasville",
      "Phoenix",
      "Rochester Hills",
      "Southfield",
      "Wilmington",
      "Doylestown",
      "Doylestown",
      "Lakeland",
      "Edina",
      "Kingwood",
      "Goshen",
      "Doylestown",
      "Westminster",
      "Ste. Genevieve",
      "Rock Island",
      "Miami",
      "Nashua",
      "Overland Park",
      "Columbus",
      "Las Vegas",
      "Las Vegas",
      "Southfield",
      "Spokane",
      "Powhatan",
      "Freehold",
      "Atlanta",
      "Orlando",
      "Parsippany",
      "Duluth",
      "Tampa",
      "Wheeling",
      "Washington",
      "Garner",
      "Springfield",
      "Springfield",
      "Warrenton",
      "Birmingham",
      "Houston",
      "North Garden",
      "Waynesville",
      "Chipley",
      "Oakland",
      "Pasadena",
      "Richardson",
      "Portsmouth",
      "Wellington",
      "Cerritos",
      "Boynton Beach",
      "Lehigh Acres",
      "Las Vegas",
      "Clayton",
      "Mission Viejo",
      "Philadelphia",
      "Dripping Springs",
      "Asheville",
      "Lubbock",
      "Oakdale",
      "Miami",
      "Stroudsburg",
      "Columbus",
      "Rolling Meadows",
      "Miami",
      "Greensboro",
      "Newtown",
      "Newtown",
      "Bedford",
      "Edmond",
      "Edmond",
      "Tallahassee",
      "Des Moines",
      "Los Angeles",
      "Chicago",
      "Tallahassee",
      "Coral Gables",
      "Huntsville",
      "Southlake",
      "Merrimack",
      "Hamden",
      "Round Rock",
      "Bridgeport",
      "Centennial",
      "Greenville",
      "Macon",
      "Faribault",
      "Bountiful",
      "Phoenix",
      "Atlanta",
      "Tavares",
      "Laurel",
      "Monmouth Junction",
      "Livingston",
      "Los Angeles",
      "Murray",
      "La Jolla",
      "Sanford",
      "Augusta",
      "New York",
      "Des Peres",
      "Brunswick",
      "Oaks",
      "Forest",
      "De Forest",
      "Naples",
      "Detroit",
      "New York",
      "Van Nuys",
      "Lakewood",
      "Myrtle Beach",
      "Prairieville",
      "Braintree",
      "Vestavia Hills",
      "Anniston",
      "Brookfield",
      "Springfield",
      "Durham",
      "New Haven",
      "Fayetteville",
      "Fayetteville",
      "Bloomington",
      "Austin",
      "Panama City",
      "Maplewood",
      "Phoenix",
      "Visalia",
      "Norman",
      "Palm Desert",
      "Tallahassee",
      "Tampa",
      "Baltimore",
      "Lincoln",
      "Salt Lake City",
      "Port Charlotte",
      "Wilmington",
      "Dallas",
      "Rochester",
      "Humble",
      "St. Louis",
      "Duluth",
      "Indianapolis",
      "St. George",
      "Las Vegas",
      "Henderson",
      "San Antonio",
      "Richmond",
      "Denver",
      "Belcourt",
      "Greensboro",
      "Salt Lake City",
      "Lexington",
      "Miami",
      "Highland Village",
      "Buena Park",
      "Chicago",
      "Geneva",
      "Bakersfield",
      "McKinney",
      "Fort Washington",
      "Fort Washington",
      "Lawrence",
      "Winder",
      "Chula Vista",
      "Royersford",
      "Fort Mitchell",
      "Smyrna",
      "Charlottesville",
      "Fredericksburg",
      "Palm Beach Gardens",
      "Aiken",
      "Salt Lake City",
      "Salt Lake City",
      "Atlanta",
      "Warwick",
      "Sylvania",
      "Los Angeles",
      "Boston",
      "Yonkers",
      "Boise",
      "Westfield Center",
      "Salt Lake City",
      "Sidney",
      "Madison",
      "Salt Lake City"
    ];

    this.bank_location_state = [
      "CA",
      "VA",
      "FL",
      "FL",
      "FL",
      "MA",
      "MO",
      "WI",
      "TX",
      "NE",
      "CA",
      "MO",
      "CT",
      "TX",
      "UT",
      "IL",
      "IL",
      "AL",
      "AL",
      "FL",
      "IL",
      "MN",
      "CA",
      "CA",
      "GA",
      "CA",
      "CO",
      "FL",
      "MI",
      "GA",
      "UT",
      "UT",
      "CA",
      "IN",
      "GA",
      "TX",
      "MI",
      "CA",
      "TX",
      "AZ",
      "MO",
      "IL",
      "MI",
      "TX",
      "PA",
      "FL",
      "CT",
      "CA",
      "TX",
      "NV",
      "AZ",
      "TX",
      "CA",
      "MT",
      "NJ",
      "CA",
      "TX",
      "TX",
      "NJ",
      "MA",
      "AZ",
      "FL",
      "MD",
      "IL",
      "FL",
      "NV",
      "GA",
      "SD",
      "ND",
      "CA",
      "KY",
      "NC",
      "MD",
      "UT",
      "NJ",
      "GA",
      "FL",
      "IL",
      "TX",
      "CA",
      "CA",
      "CA",
      "CA",
      "FL",
      "CA",
      "CA",
      "TN",
      "CA",
      "UT",
      "TN",
      "IL",
      "NC",
      "OH",
      "OR",
      "GA",
      "SC",
      "VA",
      "TX",
      "NM",
      "MS",
      "GA",
      "NY",
      "NY",
      "FL",
      "UT",
      "AZ",
      "FL",
      "NC",
      "SC",
      "RI",
      "TX",
      "AZ",
      "NC",
      "OH",
      "CA",
      "GA",
      "ID",
      "TX",
      "NE",
      "FL",
      "GA",
      "VA",
      "NJ",
      "GA",
      "IA",
      "CO",
      "CA",
      "OR",
      "TX",
      "TX",
      "WA",
      "CA",
      "VA",
      "MI",
      "IL",
      "KS",
      "MT",
      "WI",
      "SD",
      "VA",
      "MT",
      "PA",
      "CA",
      "NY",
      "UT",
      "UT",
      "NV",
      "MA",
      "CT",
      "NV",
      "FL",
      "WI",
      "NV",
      "TX",
      "NJ",
      "AL",
      "AL",
      "NJ",
      "GA",
      "FL",
      "MA",
      "IL",
      "IL",
      "CA",
      "FL",
      "AZ",
      "IN",
      "GA",
      "GA",
      "AZ",
      "CO",
      "FL",
      "FL",
      "NM",
      "TX",
      "CA",
      "GA",
      "KY",
      "MI",
      "VA",
      "AZ",
      "FL",
      "FL",
      "FL",
      "NY",
      "TN",
      "NC",
      "IN",
      "GA",
      "VA",
      "TX",
      "WI",
      "TN",
      "NJ",
      "TX",
      "VA",
      "ND",
      "FL",
      "FL",
      "FL",
      "AZ",
      "CA",
      "AL",
      "MO",
      "GA",
      "NY",
      "CA",
      "UT",
      "DE",
      "DE",
      "UT",
      "NY",
      "IL",
      "IL",
      "UT",
      "MI",
      "OH",
      "OK",
      "IL",
      "NC",
      "CT",
      "NC",
      "TX",
      "TX",
      "NY",
      "FL",
      "NY",
      "MA",
      "NJ",
      "CT",
      "UT",
      "NY",
      "OR",
      "KS",
      "PA",
      "TX",
      "PA",
      "CA",
      "GA",
      "TN",
      "CA",
      "DE",
      "CO",
      "CT",
      "TN",
      "TX",
      "OK",
      "FL",
      "WA",
      "FL",
      "CA",
      "NC",
      "GA",
      "NV",
      "GA",
      "WA",
      "LA",
      "CO",
      "UT",
      "UT",
      "MI",
      "WA",
      "TX",
      "CA",
      "MA",
      "NC",
      "TX",
      "CO",
      "WI",
      "NY",
      "NY",
      "UT",
      "UT",
      "CA",
      "UT",
      "UT",
      "MD",
      "CT",
      "NV",
      "UT",
      "CA",
      "FL",
      "TX",
      "MO",
      "GA",
      "AZ",
      "MI",
      "MI",
      "DE",
      "PA",
      "PA",
      "GA",
      "MN",
      "TX",
      "IN",
      "PA",
      "CO",
      "MO",
      "IL",
      "FL",
      "NH",
      "KS",
      "OH",
      "NV",
      "NV",
      "MI",
      "WA",
      "VA",
      "NJ",
      "GA",
      "FL",
      "NJ",
      "GA",
      "FL",
      "IL",
      "DC",
      "NC",
      "MA",
      "MA",
      "VA",
      "AL",
      "TX",
      "VA",
      "NC",
      "FL",
      "CA",
      "CA",
      "TX",
      "NH",
      "CO",
      "CA",
      "FL",
      "FL",
      "NV",
      "MO",
      "CA",
      "PA",
      "TX",
      "NC",
      "TX",
      "MN",
      "FL",
      "PA",
      "GA",
      "IL",
      "FL",
      "NC",
      "PA",
      "PA",
      "NH",
      "OK",
      "OK",
      "FL",
      "IA",
      "CA",
      "IL",
      "FL",
      "FL",
      "AL",
      "TX",
      "NH",
      "CT",
      "TX",
      "CT",
      "CO",
      "SC",
      "GA",
      "MN",
      "UT",
      "AZ",
      "GA",
      "FL",
      "MD",
      "NJ",
      "NJ",
      "CA",
      "UT",
      "CA",
      "ME",
      "GA",
      "NY",
      "MO",
      "GA",
      "PA",
      "VA",
      "WI",
      "FL",
      "MI",
      "NY",
      "CA",
      "CO",
      "SC",
      "LA",
      "MA",
      "AL",
      "AL",
      "WI",
      "MO",
      "NC",
      "CT",
      "GA",
      "GA",
      "IL",
      "TX",
      "FL",
      "MN",
      "AZ",
      "CA",
      "OK",
      "CA",
      "FL",
      "FL",
      "MD",
      "RI",
      "UT",
      "FL",
      "DE",
      "TX",
      "MN",
      "TX",
      "MO",
      "GA",
      "IN",
      "UT",
      "NV",
      "NV",
      "TX",
      "VA",
      "CO",
      "ND",
      "NC",
      "UT",
      "KY",
      "FL",
      "TX",
      "CA",
      "IL",
      "NY",
      "CA",
      "TX",
      "PA",
      "PA",
      "MA",
      "GA",
      "CA",
      "PA",
      "KY",
      "GA",
      "VA",
      "VA",
      "FL",
      "SC",
      "UT",
      "UT",
      "GA",
      "NY",
      "OH",
      "CA",
      "MA",
      "NY",
      "ID",
      "OH",
      "UT",
      "NE",
      "WI",
      "UT"
    ];

    this.bank_date_agency_action = [
      "March 5, 2007",
      "May 7, 2008",
      "June 15, 2007",
      "November 7, 2007",
      "October 21, 2008",
      "June 12, 2000",
      "July 1, 1998",
      "September 9, 1998",
      "July 27, 2007",
      "November 2, 2007",
      "February 21, 2007",
      "December 20, 2007",
      "December 28, 1999",
      "December 25, 2007",
      "June 23, 2005",
      "June 4, 1999",
      "September 15, 1998",
      "April 13, 2011",
      "June 30, 2015",
      "August 13, 2008",
      "February 22, 2007",
      "December 16, 1999",
      "January 4, 2007",
      "March 14, 2002",
      "July 26, 2007",
      "September 4, 2007",
      "November 8, 2007",
      "July 13, 2007",
      "December 1, 2008",
      "January 19, 2007",
      "September 11, 2007",
      "May 19, 2008",
      "January 11, 1999",
      "June 6, 2000",
      "February 7, 2007",
      "January 23, 2007",
      "November 12, 1999",
      "October 31, 2008",
      "March 9, 2009",
      "January 9, 2007",
      "November 4, 2010",
      "September 24, 2008",
      "September 24, 2008",
      "May 30, 2017",
      "November 27, 2013",
      "February 8, 2007",
      "August 22, 2008",
      "October 3, 2007",
      "November 2, 2007",
      "June 19, 2007",
      "March 30, 2000",
      "December 4, 2007",
      "June 14, 2007",
      "February 6, 2007",
      "March 9, 2007",
      "July 1, 1998",
      "April 26, 2007",
      "December 11, 2007",
      "March 13, 2007",
      "August 18, 2005",
      "September 14, 2007",
      "May 21, 2009",
      "July 9, 2010",
      "June 14, 2000",
      "January 18, 2005",
      "July 23, 2004",
      "February 4, 1999",
      "November 2, 2007",
      "March 23, 2007",
      "October 3, 2016",
      "November 10, 2008",
      "December 12, 2007",
      "April 11, 2008",
      "August 6, 1999",
      "October 5, 2000",
      "February 26, 2007",
      "July 17, 2008",
      "August 7, 2008",
      "August 2, 2007",
      "May 11, 2007",
      "July 28, 2000",
      "November 25, 2008",
      "August 1, 2007",
      "February 16, 2007",
      "February 5, 2007",
      "December 8, 1999",
      "February 2, 2007",
      "June 17, 2008",
      "March 20, 2007",
      "July 8, 2008",
      "February 5, 2008",
      "May 24, 2007",
      "January 17, 2007",
      "April 25, 2007",
      "June 7, 2000",
      "January 21, 2011",
      "June 27, 2007",
      "May 14, 2008",
      "January 22, 2010",
      "February 28, 2008",
      "May 19, 2008",
      "October 12, 2007",
      "December 15, 2005",
      "October 4, 1999",
      "October 11, 2000",
      "November 7, 2007",
      "March 2, 2007",
      "April 10, 2009",
      "October 1, 2008",
      "April 21, 2009",
      "July 2, 2007",
      "December 20, 2007",
      "June 13, 2008",
      "March 5, 2007",
      "September 11, 2007",
      "January 29, 2010",
      "March 13, 2007",
      "February 8, 2007",
      "November 28, 2007",
      "February 20, 2007",
      "June 26, 2007",
      "July 16, 2008",
      "June 20, 2008",
      "August 11, 2008",
      "June 24, 1997",
      "January 30, 2008",
      "April 5, 2007",
      "December 7, 2007",
      "October 14, 1997",
      "April 28, 1998",
      "November 27, 2007",
      "December 29, 2015",
      "August 20, 2008",
      "June 26, 2000",
      "February 15, 2000",
      "August 17, 2007",
      "December 22, 2000",
      "July 13, 1998",
      "October 3, 2005",
      "April 24, 2006",
      "July 19, 2006",
      "December 22, 2000",
      "October 27, 2006",
      "October 3, 2007",
      "April 8, 2002",
      "July 26, 1999",
      "July 1, 1999",
      "September 7, 1999",
      "April 4, 2008",
      "March 20, 2007",
      "January 12, 2007",
      "June 7, 2007",
      "March 21, 2007",
      "April 20, 2007",
      "March 13, 2007",
      "December 13, 2007",
      "September 7, 2007",
      "March 7, 2007",
      "March 5, 2007",
      "November 20, 2007",
      "April 24, 2009",
      "February 29, 2008",
      "February 19, 2008",
      "September 6, 2007",
      "December 22, 2008",
      "September 21, 2001",
      "October 27, 1998",
      "September 14, 2007",
      "May 1, 2008",
      "September 20, 2007",
      "March 14, 2000",
      "June 25, 2009",
      "May 28, 2008",
      "November 26, 2007",
      "April 11, 2007",
      "May 28, 2010",
      "June 14, 2000",
      "October 14, 1997",
      "January 29, 2007",
      "November 20, 2007",
      "July 15, 2008",
      "May 29, 2007",
      "August 9, 2007",
      "November 14, 2007",
      "March 7, 2007",
      "April 24, 2007",
      "February 22, 2008",
      "July 28, 1998",
      "November 20, 2007",
      "October 30, 2007",
      "October 24, 2007",
      "August 1, 2000",
      "October 31, 2007",
      "April 10, 2008",
      "January 17, 2007",
      "January 3, 2008",
      "May 16, 2000",
      "July 27, 1999",
      "March 14, 2007",
      "March 5, 2008",
      "November 27, 2007",
      "September 17, 2008",
      "July 17, 2008",
      "May 26, 2000",
      "March 16, 2007",
      "July 2, 2008",
      "November 13, 2008",
      "June 25, 2004",
      "May 5, 2000",
      "August 9, 2001",
      "February 28, 2003",
      "September 27, 2007",
      "April 11, 2007",
      "July 25, 2007",
      "July 21, 2003",
      "March 10, 2009",
      "June 4, 1999",
      "May 27, 2008",
      "July 28, 1998",
      "October 2, 2007",
      "December 23, 1997",
      "September 23, 2005",
      "January 18, 2008",
      "September 11, 2000",
      "April 20, 1999",
      "June 29, 2007",
      "June 20, 2008",
      "June 18, 2013",
      "May 12, 2008",
      "January 11, 2000",
      "January 17, 2007",
      "July 2, 2008",
      "June 11, 2007",
      "October 21, 2010",
      "March 9, 2007",
      "April 10, 2009",
      "January 14, 2000",
      "June 22, 2004",
      "November 20, 2007",
      "March 9, 2004",
      "June 12, 2017",
      "August 3, 2000",
      "March 30, 2001",
      "March 13, 2001",
      "September 1, 2000",
      "June 28, 2007",
      "December 5, 2016",
      "December 20, 2007",
      "July 9, 2007",
      "October 23, 2007",
      "October 30, 2007",
      "February 9, 2007",
      "June 13, 2007",
      "March 21, 2008",
      "August 8, 2007",
      "December 7, 2007",
      "October 7, 2009",
      "May 1, 2007",
      "November 4, 2005",
      "August 10, 2005",
      "August 6, 2007",
      "May 7, 2008",
      "June 6, 2008",
      "October 17, 2007",
      "February 29, 2000",
      "April 21, 2008",
      "October 9, 2007",
      "September 26, 2007",
      "April 4, 2001",
      "February 16, 2007",
      "February 16, 2007",
      "May 18, 2005",
      "September 23, 2005",
      "October 2, 2008",
      "March 20, 2007",
      "February 12, 2008",
      "October 14, 2004",
      "December 22, 1999",
      "March 19, 2008",
      "October 2, 2003",
      "February 5, 2007",
      "October 7, 2003",
      "August 24, 2007",
      "July 1, 1998",
      "September 28, 2007",
      "September 4, 2007",
      "April 12, 2001",
      "October 7, 2003",
      "February 16, 2007",
      "January 18, 2007",
      "July 30, 2007",
      "March 21, 2008",
      "February 11, 2008",
      "August 6, 2008",
      "March 5, 2001",
      "February 12, 2008",
      "February 5, 2008",
      "May 30, 2007",
      "November 14, 2002",
      "July 16, 2010",
      "July 24, 2007",
      "June 6, 2001",
      "July 1, 1998",
      "January 23, 2007",
      "July 30, 2008",
      "April 30, 1999",
      "February 24, 1998",
      "November 4, 2008",
      "October 30, 2007",
      "March 24, 1998",
      "July 25, 2008",
      "June 12, 2000",
      "December 21, 2007",
      "June 5, 2007",
      "September 28, 2007",
      "March 16, 2007",
      "August 3, 2007",
      "November 20, 2007",
      "March 6, 2008",
      "November 3, 2008",
      "March 5, 2008",
      "January 29, 2007",
      "February 9, 2007",
      "May 18, 2007",
      "July 3, 2008",
      "April 27, 2007",
      "March 5, 2009",
      "May 1, 2007",
      "September 19, 2007",
      "July 25, 2007",
      "March 27, 2007",
      "January 23, 2008",
      "April 27, 2007",
      "March 2, 2007",
      "March 20, 2008",
      "May 22, 2007",
      "March 19, 1999",
      "April 23, 2007",
      "November 15, 2007",
      "May 24, 2007",
      "January 29, 2007",
      "July 13, 2001",
      "June 6, 1997",
      "May 5, 2000",
      "April 18, 2007",
      "January 22, 2010",
      "March 13, 2008",
      "June 4, 2007",
      "September 14, 2007",
      "March 9, 2015",
      "March 24, 2008",
      "April 2, 2008",
      "September 14, 2007",
      "December 16, 1997",
      "August 19, 2005",
      "September 9, 2008",
      "May 10, 2007",
      "February 27, 2008",
      "November 29, 2007",
      "April 25, 2007",
      "February 28, 2007",
      "February 22, 2008",
      "February 25, 2009",
      "February 17, 2005",
      "May 14, 2008",
      "October 9, 2008",
      "January 31, 2008",
      "May 21, 2007",
      "October 18, 1999",
      "April 23, 2007",
      "January 29, 2008",
      "August 29, 2008",
      "October 26, 2007",
      "June 12, 2008",
      "November 5, 2007",
      "September 23, 2008",
      "October 26, 2005",
      "July 26, 2006",
      "December 18, 2008",
      "February 2, 2007",
      "June 22, 2007",
      "May 5, 2008",
      "August 20, 2007",
      "September 29, 2000",
      "May 17, 2007",
      "October 17, 2007",
      "April 27, 2007",
      "April 9, 1998",
      "April 3, 2001",
      "July 1, 2008",
      "March 22, 2007",
      "September 28, 2007",
      "June 10, 2008",
      "March 17, 1998",
      "October 1, 2007",
      "April 18, 2007",
      "February 27, 2008",
      "September 22, 2008",
      "July 1, 2005",
      "December 3, 2010",
      "June 6, 2007",
      "October 31, 2007",
      "November 17, 1998",
      "September 26, 2008",
      "February 29, 2008",
      "April 12, 2007",
      "March 27, 2007",
      "March 19, 2008",
      "February 25, 2008",
      "February 26, 2007",
      "May 10, 2007",
      "April 14, 2011",
      "September 13, 1999",
      "April 27, 2000",
      "August 27, 2004",
      "March 31, 1998", 
      "July 14, 2000",
      "December 7, 2007",
      "May 21, 2007",
      "November 21, 2007",
      "July 1, 1998",
      "October 12, 2007",
      "May 11, 2007",
      "February 26, 2007",
      "July 7, 2005",
      "January 13, 2004",
      "April 5, 2007",
      "January 29, 2008",
      "March 3, 2000",
      "May 18, 2007",
      "July 12, 2000",
      "September 9, 2003",
      "September 14, 1999",
      "August 9, 2001",
      "March 17, 1998",
      "September 18, 2001",
      "August 19, 2010",
      "June 18, 2007",
      "November 13, 2008",
      "March 27, 2007",
      "March 12, 2007",
      "September 10, 2007",
      "May 7, 2007",
      "April 15, 2008",
      "July 2, 2008",
      "June 20, 2007",
      "August 23, 2002",
      "March 5, 2007",
      "June 26, 1998",
      "June 11, 2008",
      "March 31, 2000",
      "August 28, 2007",
      "December 11, 2001",
      "March 13, 2000",
      "December 28, 2006",
      "June 6, 2001",
      "March 20, 2007",
      "February 22, 2008",
      "October 15, 2008",
      "February 27, 2008",
      "March 14, 2008",
      "January 23, 2001",
      "September 30, 2003",
      "February 26, 2001",
      "September 11, 2008",
      "October 20, 2000"
    ]
  }

  createRow(name, city, state, date) {
    return (
      <tr>
        <td> <a href=''> {name} </a> </td>
        <td> {city}  </td>
        <td> {state} </td>
        <td> {date}  </td>
      </tr>
    );
  }

  createRows() {
    for (var i = 0; i < this.bank_name.length; i++) {
      
    }
  }

  createTable() {
    return (
      <table id='tableSearch' class='table table-striped table-bordered dataTable' width='100%' cellspacing='0' role='grid' aria-describedby='tableSearch_info' style='width:100%;'>
      <thead>
        <tr>
          <th> Name </th>
          <th> City </th>
          <th> State </th>
          <th> Date </th>
        </tr>
      </thead>
      <tbody>
        {this.createRows()}
      </tbody>
      </table>
    );

  }

  render() {

    return this.createTable();

  }

}


export default RaidProgress;